
# Builds will be triggered via Codemagic's REST API with the $CLIENT_ID variable and the WL_CLIENT_ID environment group in the payload
workflows:
  # Pass these variables when using this workflow: (CLIENTS[], BRANCH, APP_ID, WORKFLOW_ID) and this group (cm_credentials)
  trigger_all_workflow:
    name: Triggering build for all clients
    scripts:
      - name: Trigger Builds
        script: |
          array=($(echo "${CLIENTS}" | tr ',' ' '))
          for CLIENT in "${array[@]}"; do
            echo "Starting build for client: $CLIENT"
            curl -H "Content-Type: application/json" -H "x-auth-token: ${CM_API_KEY}" \
              --data '{
                "appId": "'$APP_ID'", 
                "workflowId": "'$WORKFLOW_ID'",
                "branch": "'$BRANCH'",
                "sshAccessEnabled":false,
                "labels": ["building-all","'$CLIENT'"],
                "environment": {
                  "variables": {
                    "CLIENT_ID": "'$CLIENT'"
                   },
                  "groups": [
                     "'wl_${CLIENT}'"
                   ]
                }
              }' \
            https://api.codemagic.io/builds
          done
